"""add relationships and foreign keys

Revision ID: 261eb53e7469
Revises: 9f0f7f089a4d
Create Date: 2024-12-09 11:31:56.494393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261eb53e7469'
down_revision: Union[str, None] = '9f0f7f089a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
